# Generated by Django 3.1.1 on 2021-06-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210626_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='continent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
