# Generated by Django 3.1.1 on 2021-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suggest_location', '0002_auto_20210626_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
    ]
